POST http://localhost:5000/auth/dlogin
Content-Type: application/json

{
    "email":"adithya@gmail.com",
    "password":"adithyawer"
}




###
GET http://192.168.155.127:5000/book/stats/684e934f85ba02d8b34baee1


###
POST http://localhost:5000/user/userrating/6823312e073bef9c00950ac1
Content-Type: application/json

{
    "newRating":4
}