POST http://localhost:5000/auth/dlogin
Content-Type: application/json

{
    "email":"adithya@gmail.com",
    "password":"adithyawer"
}



###
GET http://192.168.155.127:5000/auth/

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"adithyakadukuntla008@gmail.com",
    "password":"Adithya@2307"
}


###
GET https://servzy-bend.onrender.com/


###
POST http://localhost:5000/user/userrating/6823312e073bef9c00950ac1
Content-Type: application/json

{
    "newRating":4
}



###
post https://exp.host/--/api/v2/push/send 
Content-Type: application/json

{
                "to": "ExponentPushToken[lWLdLwEOB305_5huCQsxxA]",
                "title": "Booking Accepted!",
                "body": "Your booking has been accepted by the provider." 
}